# Database connection

There are different ways to open a connection and to get data.

Prepare database with a table

```{r}
db <- rocker::newDB() # New database handling object
db$setupSQLite(dbname = tempfile()) # Setup SQLite database
db$connect() # Open connection
db$writeTable("mtcars", mtcars) # Create table for testing
db$disconnect() # Close connection
```

__Example 1__

Get query with automatic connection / disconnection

```{r}
output <- db$getQuery("SELECT * FROM mtcars;") # Get query
```

__Example 2__

Get query with manual connection / disconnection

```{r}
db$connect() # Open connection
output1 <- db$getQuery("SELECT * FROM mtcars;") # Get query 1
output2 <- db$getQuery("SELECT * FROM mtcars;", 15) # Get query 2
db$disconnect() # Close connection
```

__Example 3__

Function getQuery() is a combination of functions sendQuery(), fetch() and clearResult().

```{r}
db$connect() # Open connection
db$sendQuery("SELECT * FROM mtcars;") # Send query
output <- db$fetch() # Fetch result
db$clearResult() # Clean up result
db$disconnect() # Close connection
```

Clean up

```{r}
db$unloadDriver() # Reset database handling object
```
